version: '3'

tasks:
  minify:
    cmds:
      - echo "Hello, world!"

  upload:
    - rsync -avh "." "nathan@degruchy.org:/var/www/degruchy.org/" --delete --filter="- .git" --filter="- Makefile" --filter="- Taskfile.yml" --filter="- assets/css/normalize*" --filter="- assets/css/resume*" --filter="- assets/css/main.css" --filter="- .gitignore" --filter="- .idea" --filter="- README.md" --filter="- .task" --delete-excluded

  default:
    - task: minify
    - task: upload
